stages:
  - mavenbuild
  - androidtry
 
maven-build: #this is a job
 stage: mavenbuild
 tags:
  - spring_tag #this is LINK to the shell runner on the remote-server
 script:
  - cd Backend/lazertag-springboot
  - mvn package -B
        
android-build: #this is another job
 image: javiersantos/android-ci:latest   #this is a directive to DOCKER
 stage: androidtry
 tags:
  - android_tag   #this is LINK to the docker runner on the remote-server
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
  script:
  - cd Frontend/TestGPS
  - ./gradlew assemble