#Example .gitlab-ci.yml
stages:
  - maventry
  - mavenbuild
  - maventest
  - androidtry
 
maven-build: #this is a job
 stage: maventry
 tags:
  - spring_tag #this is LINK to the shell runner on the remote-server
 script:
  - cd Backend/lazertag-springboot
  - mvn package
    
maven-build: #build job for springboot
 stage: mavenbuild
 tags:
  - spring_tag 
  script:
   - cd Backend/lazertag-springboot
   - mvn package -B
    
maven-build: #test job for springboot
 stage: maventest
 tags:
  - spring_tag 
 script:
  - cd Backend/lazertag-springboot
  - mvn test
 artifacts:
  paths:
   - Backend/lazertag-springboot/target/*.jar
    
android-build: #this is another job
 image: javiersantos/android-ci:latest   #this is a directive to DOCKER
 stage: androidtry
 tags:
  - android_tag   #this is LINK to the docker runner on the remote-server
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
  script:
  - cd Frontend/TestGPS/gradlew
  - ./gradlew assemble