image: maven:latest

stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  - mavenDeploy
  
maven-build: #maven build job for springboot
  stage: mavenbuild
  tags:
    - spring_tag 
  script:
    - cd Backend/lazertag-springboot
    - mvn package -B
 
maven-test: #this is a job
  stage: maventest
  tags:
    - spring_tag #this is LINK to the shell runner on the remote-server
  script:
    - cd Backend/lazertag-springboot
    - mvn test
  artifacts:
    paths:
      - Backend/lazertag-springboot/target/*.jar
        
android-build: #this is another job
 image: javiersantos/android-ci:latest   #this is a directive to DOCKER
 stage: androidbuild
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
 tags:
  - android_tag   #this is LINK to the docker runner on the remote-server
 script:
  - cd Frontend/TestGPS
  - ./gradlew assemble
 artifacts:
   paths:
   - outputs/  #TODO
   
android-test: 
 image: javiersantos/android-ci:latest   
 stage: androidtest
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
 tags:
  - android_tag   
 script:
  - cd Frontend/TestGPS
  - ./gradlew test
  
autoDeploy:
  stage: mavenDeploy
  tags:
   - spring_tag
  script:
    - cd Backend/lazertag-springboot
    - mvn package
    - mv target/*.jar /var/lib/docker/volumes/runner-ta9ucd4u-project-5924-concurrent-0-cache-c33bcaa1fd2c77edfc3893b41966cea8/_data/cs309/spring2021/mc_2/Backend/lazertag-springboot/web-demo.jar
    - systemctl stop system-web-demo
    - systemctl start system-web-demo