image: maven:latest

stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  
maven-build: #maven build job for springboot
 stage: mavenbuild
 tags:
   - spring_tag 
  script:
   - cd Backend/lazertag-springboot
   - mvn package -B
 
maven-build: #this is a job
 stage: maventest
 tags:
  - spring_tag #this is LINK to the shell runner on the remote-server
 script:
  - cd Backend/lazertag-springboot
  - mvn test
  artifacts:
    paths:
      - Backend/lazertag-springboot/target/*.jar
        
android-build: #this is another job
 image: javiersantos/android-ci:latest   #this is a directive to DOCKER
 stage: androidbuild
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
 tags:
  - android_tag   #this is LINK to the docker runner on the remote-server
 script:
  - cd Frontend/TestGPS
  - ./gradlew assemble
 artifacts:
   paths:
   - outputs/  #TODO
   
android-build: 
 image: javiersantos/android-ci:latest   
 stage: androidtest
 before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/TestGPS/gradlew
 tags:
  - android_tag   
 script:
  - cd Frontend/TestGPS
  - ./gradlew test